### ISSUE TITLE
harden-runner being added to job that already uses harden-runner

### ISSUE THREAD

**Issue by ericcornelissen** [step-security/secure-workflows#1150]
When I run [app.stepsecurity.io](https://app.stepsecurity.io/) on [a workflow from one of my projects](https://github.com/ericcornelissen/shescape/blob/16604e1b3eaa4acb83d37e75b198070c104a63ca/.github/workflows/test.yml) with the _"Add security agent for GitHub-hosted runner"_ option enabled it wants to add `step-security/harden-runner@v1` to one of the jobs that already uses it. See:

![bug preview](https://user-images.githubusercontent.com/3742559/189537444-42e907ab-9d4f-448e-b6a3-37a3c5d90045.png)

---

This is possibly related to #33

**Comment by varunsh-coder** [comment]
Thanks @ericcornelissen for reporting it!

@Devils-Knight can you please look into this? We should also add test case for it.

**Comment by varunsh-coder** [comment]
Thanks @Devils-Knight for fixing this!

@ericcornelissen this was happening in case a previous job was calling a re-usable workflow. We should not have been adding harden-runner if job calls a re-usable workflow. The fix is now deployed.
