### ISSUE TITLE
suggestion: include tag name in comment when pinning actions

### ISSUE THREAD

**Issue by ericcornelissen** [step-security/secure-workflows#1151]
This is a suggestion based on a tool called [Ratchet](https://github.com/sethvargo/ratchet)[^1] I've tried in the past. A thing I liked about this tool is that when it changes an action version tag to a SHA, it includes the tag name in a comment after the SHA.

## Current

This is an example of a diff produced by this project at the moment:

```diff
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e
         with:
           fetch-depth: 0
``` 

## Suggested

This is an example of a diff I'm suggesting this project should produce:

```diff
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2.0.3
         with:
           fetch-depth: 0
``` 

[^1]: Ratchet essentially provides the same pinning functionality as this project, but it also supports other CIs as well as the ability to update the SHA to a newer version. I didn't end up using Ratchet because it messes with the formatting of YAML files.

**Comment by varunsh-coder** [comment]
Thanks @ericcornelissen for the suggestion. I believe this is duplicate of #1087. 

If so, can you please close this one, and we can continue conversation in the other issue. Thanks!

**Comment by ericcornelissen** [comment]
Looks like you're right. I didn't manage to find that issue somehow - apologies for the noise 🙂
