### ISSUE TITLE
Please sign-off on your commits.

### ISSUE THREAD

**Issue by justinabrahms** [step-security/secure-workflows#1276]
Hi. Love the tool. It would be really helpful if you signed the commits coming out of the robot. It would make the merge much easier for my project.

Cheers,
 -justin

**Comment by varunsh-coder** [comment]
This has been implemented. Here is an example: https://github.com/boahc077/playground/pull/47. Please let me know if this looks ok. 

Also, similar to the feature to fix issues in a repo, we are working on a dashboard across repos in a GitHub org. I have setup this dashboard for the public repos of `open-feature` org. You can access it using your GitHub account. 
https://app.stepsecurity.io/github/app/open-feature/open-feature/repositories

Please let me know your feedback. Thanks!

**Comment by justinabrahms** [comment]
Looks right to me. :)
