### ISSUE TITLE
[BUG] Secure-Workflows adds harden-runner with old tag.

### ISSUE THREAD

**Issue by h0x0er** [step-security/secure-workflows#1313]
If action pinning in disabled in `https://app.stepsecurity.io/secure-workflows`; then the `harden-runner action` is always added with `@v1` tag. The latest tag is not added.

![image](https://user-images.githubusercontent.com/84621253/195759855-c1d5dad9-acdf-49b4-8236-1e04278fd8c3.png)

**Refer**
https://github.com/step-security/secure-workflows/blob/271e465ba8ae63db24252f69b0b10ff8bcdd1b45/secureworkflow.go#L8
https://github.com/step-security/secure-workflows/blob/271e465ba8ae63db24252f69b0b10ff8bcdd1b45/secureworkflow.go#L67

**Comment by varunsh-coder** [comment]
@h0x0er `v1` is the latest tag. Each time a new version is released, e.g. `v1.5.0`, `v1` tag is updated to point to it. 

You can check here: https://github.com/step-security/harden-runner/tags

**Comment by h0x0er** [comment]
@varunsh-coder Thanks for the info, it cleared the doubt :)
