### ISSUE TITLE
Auto-generated commit messages are garbled

### ISSUE THREAD

**Issue by kmk3** [step-security/secure-workflows#1369]
### Problem

The commit message is missing a blank line between the title and the body.

This causes the SOB trailer to be treated as part of the commit message title,
which makes it over 90 characters long.

From <https://github.com/netblue30/firejail/pull/5439/>:

Actual behavior:

```console
$ git log --no-decorate --oneline -n 3 d8a5f385b
d8a5f385b [StepSecurity] ci: Harden GitHub Actions Signed-off-by: StepSecurity Bot <bot@stepsecurity.io>
b3671db0b build(deps): bump github/codeql-action from 2.1.28 to 2.1.29
e24eadec1 Fix freetube mpris support
$ git show --pretty='%s%n%n%b' -s d8a5f385b
[StepSecurity] ci: Harden GitHub Actions Signed-off-by: StepSecurity Bot <bot@stepsecurity.io>


$ git show --pretty=%s -s d8a5f385b | tr -d '\n' | wc -m
94
```

Expected behavior:

```console
$ git log --no-decorate --oneline -n 3 d8a5f385b
d8a5f385b [StepSecurity] ci: Harden GitHub Actions
b3671db0b build(deps): bump github/codeql-action from 2.1.28 to 2.1.29
e24eadec1 Fix freetube mpris support
$ git show --pretty='%s%n%n%b' -s d8a5f385b
[StepSecurity] ci: Harden GitHub Actions

Signed-off-by: StepSecurity Bot <bot@stepsecurity.io>
$ git show --pretty=%s -s d8a5f385b | tr -d '\n' | wc -m
40
```

Working example from dependabot:

```console
$ git show --pretty='%s%n%n%b' -s b3671db0b
build(deps): bump github/codeql-action from 2.1.28 to 2.1.29

Bumps [github/codeql-action](https://github.com/github/codeql-action) from 2.1.28 to 2.1.29.
- [Release notes](https://github.com/github/codeql-action/releases)
- [Changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md)
- [Commits](https://github.com/github/codeql-action/compare/cc7986c02bac29104a72998e67239bb5ee2ee110...ec3cf9c605b848da5f1e41e8452719eb1ccfb9a6)

---
updated-dependencies:
- dependency-name: github/codeql-action
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>
```

### Misc

I tried to find where the commit message is generated in this repository, but I
couldn't find it:

```console
$ git show --pretty='%h %ai %s' -s
ed7272f 2022-10-03 21:53:22 -0700 Merge pull request #1267 from step-security/add-scorecard-badge
$ git grep -e ci: -e 'Harden GitHub' -e SOB -e Signed-off -e bot@stepsecurity.io
$
```

**Comment by varunsh-coder** [comment]
Thanks a lot @kmk3 for reporting. Will get this addressed ASAP. 

The code that creates fork and PR is not in this repo, which is why you could not find it here.

**Comment by boahc077** [comment]
Thank you @kmk3 for finding this issue, we have deployed a remediation for it. It would be really helpful for us if you could try it out and let me know if it doesn't work for you.

**Comment by kmk3** [comment]
Thanks for the quick response and fix.

The message looks correct now:

From <https://github.com/kmk3/firejail/pull/19>:

```console
$ git show --pretty='%s%n%n%b' -s d8f1e0376
[StepSecurity] ci: Harden GitHub Actions

Signed-off-by: StepSecurity Bot <bot@stepsecurity.io>
```

**Comment by kmk3** [comment]
> The code that creates fork and PR is not in this repo, which is why you could
> not find it here.

I see; is that other repo public by any chance?  I'm kind of curious to see how
the original bug happened code-wise, as I'm unfamiliar with using automation to
write commit messages.

**Comment by boahc077** [comment]
Hello @kmk3,

We use `(google/go-github)[https://github.com/google/go-github]` for all GitHub operations. Earlier, we were using only one `\n`. After investigating this bug, we realized that we needed to put two new line characters (please see the diff below).
<img width="378" alt="Screen Shot 2022-11-13 at 3 22 28 PM" src="https://user-images.githubusercontent.com/100655670/201550137-e8492838-1986-4a88-b28c-a99ce60e8fec.png">

**Comment by kmk3** [comment]
> Hello @kmk3,
> 
> We use [`google/go-github`](https://github.com/google/go-github) for all
> GitHub operations. Earlier, we were using only one `\n`. After investigating
> this bug, we realized that we needed to put two new line characters (please
> see the diff below).
> 
> <img alt="Screen Shot 2022-11-13 at 3 22 28 PM" width="378" src="https://user-images.githubusercontent.com/100655670/201550137-e8492838-1986-4a88-b28c-a99ce60e8fec.png">

That makes sense; thanks for the details!
