### ISSUE TITLE
Move all KB issues into a single issue

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-workflows#1376]
We have lot of KB issues that makes it hard to find rest of the issues. 

We should move all KB issues into a single issue. 

When a new KB has to be added, it can be added to the description of that issue. It could be added as a check box
e.g. 

- [ ] Add GitHub token permissions for jitterbit/get-changed-files Action
- [ ] Add GitHub token permissions for actions/upload-pages-artifact Action

**Comment by varunsh-coder** [comment]
@h0x0er please take this up. Please move all open KB issues into this new issue, and close the existing ones. You can use automation for this via GitHub Actions.

**Comment by varunsh-coder** [comment]
I ran this and it only closed one issue. Not sure why...
https://github.com/step-security/secure-workflows/actions/runs/3425663808/jobs/5706665941

**Comment by h0x0er** [comment]
@varunsh-coder I just created a PR to fix the issue. Thanks !!

**Comment by varunsh-coder** [comment]
It again only closed one :)

**Comment by varunsh-coder** [comment]
I was running last pinned version. Updated it and it ran fine this time.

**Comment by h0x0er** [comment]
I haven't  added pagination support.. so as of now It only closes 100 issues in one go..  I will make changes and let you know..

**Comment by varunsh-coder** [comment]
> 

That’s fine. We can run it multiple times. No need for pagination
