### ISSUE TITLE
Update token permission logic

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-workflows#159]
- [ ] Set workflow level permission to `contents: read`
- [ ] Do not set job level permission if it is `contents: read`

https://github.com/Automattic/vip-go-mu-plugins/pull/2815#discussion_r786933173
https://github.com/actions/starter-workflows/pull/1341#discussion_r786995370

**Comment by varunsh-coder** [comment]
@h0x0er can you please take this up?

**Comment by h0x0er** [comment]
@varunsh-coder sure, I will handle this
