### ISSUE TITLE
Permissions UI editor not visible for specific repository on Firefox 108

### ISSUE THREAD

**Issue by tuminoid** [step-security/secure-workflows#1793]
In the permissions editor view, the editor is not visible at all regardless of options used on Firefox 108:
https://app.stepsecurity.io/secureworkflow/metal3-io/metal3-io.github.io/jekyll.yml/source?enable=permissions

Screenshot (on Firefox 108):
![image](https://user-images.githubusercontent.com/853790/211296557-dda9b858-1e1e-4147-8d53-e780df42298f.png)

In Google Chrome, the link and editor are visible. In general, the views work on Firefox as well, this link is an exception for me.

**Comment by varunsh-coder** [comment]
Thanks, @tuminoid, for using secure workflows and creating this issue. I'll look into this and get back to you soon. Thanks!

**Comment by varunsh-coder** [comment]
@eppisai can you please investigate?

**Comment by eppisai** [comment]
Hi @tuminoid,
I am using firefox 108 with macOS ventura, i haven't been able to recreate the issue on my end.. can you please confirm if its coming at your end?

Below is how i tried to recreate it,

https://user-images.githubusercontent.com/54789531/213253451-d1d4baa5-d9fd-4081-9ae1-855821bbec1d.mp4

**Comment by tuminoid** [comment]
Hi @eppisai, it is at the moment no longer reproducable on my end either. Single the issue was opened we have changed the contents of workflow file (adding top-level permissions etc) and you have added the actions used in the workflow to your database. Perhaps it was combination of those that caused the issue. I can't think of anything else that would've changed on my end, and it was very speciifc to this workflow view.

It's ok for me to close as fluke, if you cannot reproduce it. Thanks for checking!

**Comment by varunsh-coder** [comment]
thanks @tuminoid and @eppisai! I am closing this for now. Feel free to re-open if you see the issue again.
