### ISSUE TITLE
Update KB analysis workflow

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-workflows#1833]
We should update the KB analysis automation to do the following when we have a missing KB:

1. Create a new PR into the `knowledge-base` branch
2. The PR should only have a single Action's KB
3. Do not create an issue for the Action's KB

This way, each KB can be triaged and merged separately. We can also tag the action owner in the PR to ask for feedback on permissions. 

The `knowledge-base` branch can be merged into `main` once a few new KBs are created.

**Comment by varunsh-coder** [comment]
@h0x0er please take this up

**Comment by varunsh-coder** [comment]
@h0x0er I merged the changes. 

When I tried it for wait-for-secrets action, the PR was created at first. 
https://github.com/step-security/secure-workflows/actions/runs/3982631044

Then I tried it again, and it closed the PR. 
https://github.com/step-security/secure-workflows/actions/runs/3982637188/jobs/6827273679

If the PR already exists, the CreatePR step should not run again in the workflow.

**Comment by h0x0er** [comment]
@varunsh-coder I had fixed the issue and created a PR. I had tested the fix [here](https://github.com/h0x0er/kb_setup/actions/runs/3983368984)

**Comment by varunsh-coder** [comment]
Thanks! Do you need similar updates here?
https://github.com/step-security/secure-workflows/blob/715ad09a742da22e381d739082ad4150ec6245d4/kbanalysis/src/index.ts#L37

and here

https://github.com/step-security/secure-workflows/blob/715ad09a742da22e381d739082ad4150ec6245d4/kbanalysis/src/index.ts#L77

**Comment by h0x0er** [comment]
@varunsh-coder Thanks for pointing those issues as well. I am updating the PR with the fixes

**Comment by varunsh-coder** [comment]
Worked fine now—closing issue. Thanks!
