### ISSUE TITLE
Shorten comment line in the CodeQL template

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-workflows#1850]
Based on feedback from https://github.com/statnett/controller-runtime-viper/pull/27

**Comment by varunsh-coder** [comment]
@arjundashrath please take this up. 

CodeQL template is here: https://github.com/step-security/secure-workflows/blob/main/workflow-templates/codeql.yml

Please run YAML lint locally to check.

**Comment by arjundashrath** [comment]
@varunsh-coder can I delete the comment? the link itself is 170 characters long and the limit is around 120. So the only way to split the comment is to split the URL

**Comment by varunsh-coder** [comment]
Yes, go ahead and delete the comment.
