### ISSUE TITLE
Change permission reason logic

### ISSUE THREAD

**Issue by arjundashrath** [step-security/secure-workflows#221]
The current permissions reason logic only allows permissions to begin from "to" which may not be the case in some situations. I personally encountered this problem as the test cases failed for a KB commit

**Comment by varunsh-coder** [comment]
The reason is used to create a sentence, e.g.

```
permissions:
      contents: read # for actions/checkout to fetch code
      statuses: write # for github/super-linter to mark status of each linter run
```
