### ISSUE TITLE
Link to this repository from the site

### ISSUE THREAD

**Issue by mjpieters** [step-security/secure-workflows#241]
Add a link to this repository from https://app.stepsecurity.io/ so it is easier to locate for feedback.

**Comment by varunsh-coder** [comment]
@mjpieters Thanks for the feedback. I will get this done. When one clicks `secure workflow` button, there is a line that shows up to star the repo, which has a link, but it does not render well on a mobile (related to the other issue you created). I will get a permanent link added to make it clear.

**Comment by mjpieters** [comment]
> When one clicks `secure workflow` button, there is a line that shows up to star the repo, which has a link

That's really hard to discover! Sometimes you want to just explore the project and the background, including looking at the repository, _before_ clicking on any buttons.

**Comment by varunsh-coder** [comment]
> > When one clicks `secure workflow` button, there is a line that shows up to star the repo, which has a link
> 
> That's really hard to discover! Sometimes you want to just explore the project and the background, including looking at the repository, _before_ clicking on any buttons.

Makes sense. I have updated the UI. Please see if it looks better now https://app.stepsecurity.io. There is a button with GitHub logo that goes to the repo. Is this ok? Do let me know if you have ideas to make the UI more intuitive. 

The site is still not mobile friendly, working on that...

**Comment by mjpieters** [comment]
Yes, the GH button is nice and explicit, thanks for adding that!
