### ISSUE TITLE
Permissions not added for Checkmarx workflow

### ISSUE THREAD

**Issue by Devils-Knight** [step-security/secure-workflows#255]
[Step-Security App](https://app.stepsecurity.io/) isn't adding permissions to [Checkmarx Action](https://github.com/actions/starter-workflows/blob/main/code-scanning/checkmarx.yml) according to [Chekmarx Knowledge Base](https://github.com/step-security/secure-workflows/blob/main/knowledge-base/checkmarx-ts/checkmarx-cxflow-github-action/action-security.yml).

**Comment by varunsh-coder** [comment]
@Devils-Knight this may be because the KB has both environment variable and input name. I don't think the checkmarx action takes it from the environment variable...
