### ISSUE TITLE
Is this valid?

### ISSUE THREAD

**Issue by arjundashrath** [step-security/secure-workflows#310]
@varunsh-coder the tool returns the following permission
```
    permissions:
      contents: none
```
is this valid? It returns it for https://github.com/actions/starter-workflows/blob/ba97234b6070487094b58c0bd01959c47d29c20d/deployments/azure-container-webapp.yml

**Comment by varunsh-coder** [comment]
Yes, it is valid, when we do not need to give any permission at all.
